### ISSUE TITLE
buck founder reward?

### ISSUE THREAD

**Issue by goodthebest** [BuckCoin/buck#7]
@BuckCoin 
Hey, do you guys have founder reward like e.g. ZEC  20% upto block height 849999 ? if yes, then what are official wallet addresses for founder reward to be sent and percentage?

**Comment by BuckCoin** [comment]
There is no founders reward in BUCK. All BUCK mining rewards go to the miner.

**Comment by goodthebest** [comment]
Another question about TX fees, what is the minimum TX fees for mining? I set 0.0004 but mining pool payout seems to be stuck?

**Comment by BuckCoin** [comment]
TX fee is 0.0001, so 0.0004 is fine. If you are using S-NOMP, you will need to deposit some amount of BUCK into your S-NOMP wallet addresses in order to have enough BUCK to cover fees. This is a standard issue on all mining pool software.

**Comment by goodthebest** [comment]
alright, when I check balance it shows zero, however when I check balance of z address then it shows a positive balance. So to which buct account I should deposit some funds, t address or z address?

**Comment by BuckCoin** [comment]
> alright, when I check balance it shows zero, however when I check balance of z address then it shows a positive balance. So to which buct account I should deposit some funds, t address or z address?

Assuming you are running S-NOMP, if you look in the logs you might see a message that says "insufficient funds" and something like "have XXXX.XX, need XXXX.XX". If you see this message, then you know you have an insufficient funds issue. An easy way to clear this issue without having to do much digging is to place a small amount of BUCK - a BUCK should be more than enough - into each of the 3 BUCK wallet addresses used by S-NOMP. Assuming everything else is setup fine, then that should clear stick payouts.

**Comment by goodthebest** [comment]
@BuckCoin got it, thanks appreciate it.
